name: Build and Push containers to GHCR

#This only runs if changes to decret itself or this workflow are made
on:
  push:
    branches:
      - main  
    paths:
      - decret/decret.py
      - .github/workflows/build-and-push.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build , Tag and Push Docker Images
              run: |
                CVES=(
                  "jessie cve-2016-3714 --dont-run"
                  "bullseye cve-2014-0160 --directory heartbleed --dont-run"
                  "bullseye cve-2020-7247 --directory opensmtpd"
                  "bullseye cve-2023-22809 --directory sudoedit"
                )

                for entry in "${CVES[@]}"; do
                  read -r distro cve options <<< "$entry"
                  echo "Building image for $cve on $distro"

                  # Build
                  python3 -m decret.decret -r "$distro" -n "${cve#cve-}" $options -s

                  # Tag 
                  docker tag "$distro/$cve" "ghcr.io/pi3dra/ci-decret/$cve:latest"
            
                  # Push 
                  docker push "ghcr.io/pi3dra/ci-decret/$cve:latest"
                done

