name: Build and Push to GHCR

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker (CVE-2016-3714)
        run: python3 -m decret.decret -r jessie -n 2016-3714 -s --only-create-dockerfile


      - name: Tag image for GHCR
        run: |
          docker tag jessie/cve-2016-3714 ghcr.io/${{ github.repository }}/cve-2016-3714:latest

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/cve-2016-3714:latest
