#name: Docker Image CI

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Build docker (CVE-2016-3714)
      run: python3 decret.py -r jessie -n 2016-3714 -s --dont-run

    - name: Test vuln (CVE-2016-3714)
      run: |
        docker run jessie/cve-2016-3714 apt-get install curl wget -y --force-yes
        docker run jessie/cve-2016-3714 convert 'https://example.com";ls "-la' out.png
        
