name: Manual CVE Tests

#This only runs after building and pushing dockers to ghcr
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/trivy-docker-test.yml

  workflow_run:
    workflows: ["Build and Push containers to GHCR"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Pull docker (CVE-2016-3714)
      run: |
        docker pull ghcr.io/pi3dra/ci-decret/cve-2016-3714:latest
        docker tag ghcr.io/pi3dra/ci-decret/cve-2016-3714:latest cve-2016-3714

    - name: Test vuln (CVE-2016-3714)
      run: |
        docker run cve-2016-3714 apt-get install curl wget -y --force-yes
        docker run cve-2016-3714 convert 'https://example.com";ls "-la' out.png
        
