name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Install RunCVM
      run: | 
          curl -s -o - https://raw.githubusercontent.com/newsnowlabs/runcvm/main/runcvm-scripts/runcvm-install-runtime.sh 
          sudo bash

    - name: Build docker (CVE-2016-3714)
      run: docker build -t dpipe ./examples/

    - name: Test vuln (CVE-2016-3714)
      run: docker run --runtime=runcvm --rm dpipe bash -c './exploit-1 2>/dev/null && expect -c '\''spawn su -c "whoami"; expect "Password:"; send "piped\r"; expect eof'\'

        
