name: Trivy CVE Tests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  trivy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy on image
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/pi3dra/ci-decret/cve-2016-3714:latest'
          format: 'json'
          output: 'trivy-results.json'

      - name: Check for CVE-2016-3714
        run: |
          echo "Looking for CVE-2016-3714 in Trivy results..."
          if ! grep -q "CVE-2016-3714" trivy-results.json; then
            echo "CVE-2016-3714 not found! Failing the job."
            exit 1
          else
            echo "CVE-2016-3714 found as expected."
          fi
